services:
  db:
    image: postgres:15.2-alpine3.17
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8080:8080
